return {
  cyberdream = {
    name = "cyberdream",
    variant = "cyberdream",
    modes = {
      n = "#5ea1ff",
      i = "#5eff6c",
      v = "#ffffff",
      t = "#f1ff5e",
      c = "#f1ff5e",
      r = "#ff6e5e",
      s = "#5eff6c",
    },
    git_branch = "#5eff6c",
    git_added = "#5eff6c",
    git_removed = "#ff6e5e",
    git_changed = "#f1ff5e",
    file = "#ffffff",
    file_modified = "#f1ff5e",
    file_readonly = "#ff6e5e",
    diagnostics = "#ff6e5e",
    diagnostics_warn = "#f1ff5e",
    diagnostics_info = "#5ea1ff",
    diagnostics_hint = "#5eff6c",
    lsp = "#5ea1ff",
    filetype = "#ffffff",
    cursor = "#ffffff",
    separator = "#3d3d3d",
    border = "#3d3d3d",
    git_untracked = "#f1ff5e",
    git_diff = "#5eff6c",
    encoding = "#ffffff",
    indent = "#3d3d3d",
    position = "#3d3d3d",
    foreground = "#ffffff",
    background = "#0d1117",
    primary = "#5ea1ff",
    shades = {
      shade_1 = "#071c2e",
      shade_2 = "#0c2a43",
      shade_3 = "#103758",
      shade_4 = "#14456d",
      shade_5 = "#185282",
      shade_6 = "#1c5f97",
      shade_7 = "#206cac",
      shade_8 = "#2479c1",
      shade_9 = "#2886d6",
      shade_10 = "#2c93eb",
    },
  },
}
