return {
  andromeda = {
    name = "andromeda",
    variant = "andromeda",
    modes = {
      n = "#00e8c6",
      i = "#ffe66d",
      v = "#d5ced9",
      V = "#d5ced9",
      ["^V"] = "#ffe66d",
      t = "#f39c12",
      ["!"] = "#f39c12",
      c = "#f39c12",
      r = "#ff00aa",
      R = "#ff00aa",
      s = "#ffe66d",
      S = "#ffe66d",
      ["^S"] = "#ffe66d",
    },
    git_branch = "#ffe66d",
    git_added = "#ffe66d",
    git_removed = "#f92672",
    git_changed = "#c74ded",
    file = "#d5ced9",
    file_modified = "#c74ded",
    file_readonly = "#f92672",
    diagnostics = "#ff00aa",
    diagnostics_warn = "#f39c12",
    diagnostics_info = "#00e8c6",
    diagnostics_hint = "#ffe66d",
    lsp = "#00e8c6",
    filetype = "#d5ced9",
    cursor = "#d5ced9",
    separator = "#2b2838",
    border = "#2b2838",
  },
}
