return {
  cyberdream = {
    name = "cyberdream",
    variant = "cyberdream",
    modes = {
      n = "#5ea1ff",
      i = "#5eff6c",
      v = "#ffffff",
      V = "#ffffff",
      ["^V"] = "#5eff6c",
      t = "#f1ff5e",
      ["!"] = "#f1ff5e",
      c = "#f1ff5e",
      r = "#ff6e5e",
      R = "#ff6e5e",
      s = "#5eff6c",
      S = "#5eff6c",
      ["^S"] = "#5eff6c",
    },
    git_branch = "#5eff6c",
    git_added = "#5eff6c",
    git_removed = "#ff6e5e",
    git_changed = "#f1ff5e",
    file = "#ffffff",
    file_modified = "#f1ff5e",
    file_readonly = "#ff6e5e",
    diagnostics = "#ff6e5e",
    diagnostics_warn = "#f1ff5e",
    diagnostics_info = "#5ea1ff",
    diagnostics_hint = "#5eff6c",
    lsp = "#5ea1ff",
    filetype = "#ffffff",
    cursor = "#ffffff",
    separator = "#3d3d3d",
    border = "#3d3d3d",
  },
}
