return {
  vscode = {
    name = "vscode",
    variant = "vscode",
    modes = {
      n = "#007acc",
      i = "#4ec9b0",
      v = "#dcdcaa",
      V = "#dcdcaa",
      ["^V"] = "#4ec9b0",
      t = "#cca700",
      ["!"] = "#cca700",
      c = "#cca700",
      r = "#f14c4c",
      R = "#f14c4c",
      s = "#4ec9b0",
      S = "#4ec9b0",
      ["^S"] = "#4ec9b0",
    },
    git_branch = "#4ec9b0",
    git_added = "#4ec9b0",
    git_removed = "#f14c4c",
    git_changed = "#cca700",
    file = "#dcdcaa",
    file_modified = "#cca700",
    file_readonly = "#f14c4c",
    diagnostics = "#f14c4c",
    diagnostics_warn = "#cca700",
    diagnostics_info = "#3794ff",
    diagnostics_hint = "#4ec9b0",
    lsp = "#007acc",
    filetype = "#dcdcaa",
    cursor = "#d4d4d4",
    separator = "#3c3c3c",
    border = "#3c3c3c",
    git_untracked = "#cca700",
    git_diff = "#4ec9b0",
    encoding = "#dcdcaa",
    indent = "#3c3c3c",
    position = "#3c3c3c",
    background = "transparent",
  },
}
