local lua_path = vim.api.nvim_get_runtime_file("lua/fancyline/init.lua", false)[1]
if lua_path then
  vim.opt.runtimepath:prepend(vim.fn.fnamemodify(lua_path, ":h:h"))
end

local presets = require("fancyline.presets")
local helpers = require("tests.helpers.setup")

describe("fancyline.presets", function()
  before_each(function()
    helpers.cleanup()
  end)

  after_each(function()
    helpers.cleanup()
  end)

  describe("preset loading", function()
    it("loads default preset", function()
      local preset = presets.load("default")
      assert.is_not_nil(preset)
      assert.is_table(preset)
      assert.is_table(preset.sections)
      assert.is_table(preset.components)
    end)

    it("loads vscode preset", function()
      local preset = presets.load("vscode")
      assert.is_not_nil(preset)
      assert.is_table(preset.sections)
      assert.is_table(preset.sections.left)
      assert.is_table(preset.sections.right)
    end)

    it("loads slim preset", function()
      local preset = presets.load("slim")
      assert.is_not_nil(preset)
      assert.is_table(preset.sections)
    end)

    it("returns empty table for unknown preset", function()
      local preset = presets.load("unknown-preset")
      assert.is_table(preset)
      assert.is_nil(next(preset))
    end)
  end)

  describe("vscode preset structure", function()
    it("has correct sections.left", function()
      local preset = presets.load("vscode")
      assert.is_table(preset.sections.left)
      local left = preset.sections.left
      assert.is_true(vim.tbl_contains(left, "file"))
      assert.is_true(vim.tbl_contains(left, "git_branch"))
      assert.is_true(vim.tbl_contains(left, "git_diff"))
      assert.is_true(vim.tbl_contains(left, "errors"))
      assert.is_true(vim.tbl_contains(left, "warnings"))
      assert.is_true(vim.tbl_contains(left, "infos"))
      assert.is_true(vim.tbl_contains(left, "hints"))
    end)

    it("has correct sections.right", function()
      local preset = presets.load("vscode")
      assert.is_table(preset.sections.right)
      local right = preset.sections.right
      assert.is_true(vim.tbl_contains(right, "lsp"))
      assert.is_true(vim.tbl_contains(right, "encoding"))
      assert.is_true(vim.tbl_contains(right, "indent"))
      assert.is_true(vim.tbl_contains(right, "position"))
      assert.is_true(vim.tbl_contains(right, "filetype"))
    end)

    it("has vscode icons configured", function()
      local preset = presets.load("vscode")
      assert.equals("󰈚", preset.components.file.icon)
      assert.equals("󰊢", preset.components.git_branch.icon)
      assert.equals("", preset.components.errors.icon)
      assert.equals("", preset.components.warnings.icon)
      assert.equals("", preset.components.infos.icon)
      assert.equals("", preset.components.hints.icon)
      assert.equals("", preset.components.encoding.icon)
      assert.equals("󰌒", preset.components.indent.icon)
      assert.equals("󰀹", preset.components.position.icon)
    end)

    it("has correct style configurations", function()
      local preset = presets.load("vscode")
      assert.equals("none", preset.components.mode.style)
      assert.equals("none", preset.components.file.style)
      assert.equals("none", preset.components.lsp.style)
      assert.equals("none", preset.components.position.style)
      assert.equals("none", preset.components.filetype.style)
    end)

    it("has filetype with icon = nil for auto-detection", function()
      local preset = presets.load("vscode")
      assert.is_nil(preset.components.filetype.icon)
      assert.is_true(preset.components.filetype.show_icon)
    end)

    it("has position with vscode format", function()
      local preset = presets.load("vscode")
      assert.equals("Ln %l, Col %c", preset.components.position.format)
    end)
  end)

  describe("brick preset structure", function()
    it("loads brick preset", function()
      local preset = presets.load("brick")
      assert.is_not_nil(preset)
      assert.is_table(preset.sections)
      assert.is_table(preset.components)
    end)

    it("has correct sections.left", function()
      local preset = presets.load("brick")
      local left = preset.sections.left
      assert.is_true(vim.tbl_contains(left, "mode"))
      assert.is_true(vim.tbl_contains(left, "file"))
      assert.is_true(vim.tbl_contains(left, "git_branch"))
      assert.is_true(vim.tbl_contains(left, "git_diff"))
    end)

    it("has correct sections.right", function()
      local preset = presets.load("brick")
      local right = preset.sections.right
      assert.is_true(vim.tbl_contains(right, "encoding"))
      assert.is_true(vim.tbl_contains(right, "errors"))
      assert.is_true(vim.tbl_contains(right, "warnings"))
      assert.is_true(vim.tbl_contains(right, "infos"))
      assert.is_true(vim.tbl_contains(right, "hints"))
      assert.is_true(vim.tbl_contains(right, "lsp"))
      assert.is_true(vim.tbl_contains(right, "position"))
    end)

    it("has empty separator", function()
      local preset = presets.load("brick")
      assert.equals("", preset.separator)
    end)

    it("has mode with bold enabled", function()
      local preset = presets.load("brick")
      assert.is_true(preset.components.mode.bold)
      assert.equals("mode", preset.components.mode.fg)
      assert.equals("shade_4", preset.components.mode.bg)
    end)

    it("has square borders on mode", function()
      local preset = presets.load("brick")
      assert.equals("square", preset.components.mode.border.left.style)
      assert.equals("square", preset.components.mode.border.right.style)
    end)

    it("has file with shade backgrounds", function()
      local preset = presets.load("brick")
      assert.equals("shade_2", preset.components.file.bg)
      assert.equals("square", preset.components.file.border.left.style)
      assert.equals("square", preset.components.file.border.right.style)
    end)

    it("has cwd component", function()
      local preset = presets.load("brick")
      assert.is_table(preset.components.cwd)
      assert.equals("shade_2", preset.components.cwd.bg)
    end)

    it("has project component", function()
      local preset = presets.load("brick")
      assert.is_table(preset.components.project)
      assert.equals("shade_2", preset.components.project.bg)
    end)

    it("has lsp component with square borders", function()
      local preset = presets.load("brick")
      assert.is_table(preset.components.lsp)
      assert.equals("shade_2", preset.components.lsp.bg)
      assert.equals("square", preset.components.lsp.border.left.style)
    end)

    it("has position with custom format", function()
      local preset = presets.load("brick")
      assert.equals("%l/%c", preset.components.position.format)
      assert.equals("shade_2", preset.components.position.bg)
    end)
  end)

  describe("all presets have required structure", function()
    local preset_names = { "default", "vscode", "slim", "brick" }

    for _, name in ipairs(preset_names) do
      it(name .. " has sections", function()
        local preset = presets.load(name)
        assert.is_table(preset.sections)
        assert.is_table(preset.sections.left)
        assert.is_table(preset.sections.right)
      end)

      it(name .. " has components", function()
        local preset = presets.load(name)
        assert.is_table(preset.components)
      end)
    end
  end)
end)
